/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Barang;

import Kategori.KategoriBrng;
import Kategori.Kontrol_Kategori;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author basisb09
 */
public class GUI_Barang extends java.awt.Dialog {

    private String folder;

    /**
     * Creates new form GUI_Barang
     */
    public GUI_Barang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        folder = System.getProperty("user.dir") + File.separator + "images";
        cetak(folder);
        new File(folder).mkdir();
        initComponents();
        this.setLocationRelativeTo(null);
        tampilisikategori();
        tombol_hapus.setEnabled(false);
        label_kode_update.setVisible(false);
        path_gambar.setVisible(false);
        path_gambar.setText("-");
        dialog_barang.setVisible(false);
        dialog_barang.setSize(1000, 600);
        dialog_barang.setLocationRelativeTo(null);
        dialog_barang.setTitle("Daftar Seluruh Barang");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_barang = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new BackgroundImage();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        teks_barcode = new javax.swing.JTextField();
        teks_namabarang = new javax.swing.JTextField();
        Combo_kategori = new javax.swing.JComboBox();
        combo_satuan = new javax.swing.JComboBox();
        teks_qtymin = new javax.swing.JTextField();
        teks_qtymax = new javax.swing.JTextField();
        teks_kodebarang = new javax.swing.JTextField();
        label_gambar = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        path_gambar = new javax.swing.JLabel();
        label_kode_update = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        teks_jualppn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        teks_jual = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        teks_belippn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        teks_beli = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        tombol_simpan = new javax.swing.JButton();
        tombol_hapus = new javax.swing.JButton();
        tombol_list = new javax.swing.JButton();
        tombol_batal = new javax.swing.JButton();
        tombol_tutup = new javax.swing.JButton();

        dialog_barang.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialog_barang.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DAFTAR SELURUH BARANG", 0, 0, new java.awt.Font("Goudy Old Style", 1, 12))); // NOI18N

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Barang", "Kategori", "Satuan", "Min", "Maks", "Harga Beli", "Harga Jual"
            }
        ));
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_barang);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442484041_exit.png"))); // NOI18N
        jButton1.setText("TUTUP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483829_Print.png"))); // NOI18N
        jButton2.setText("CETAK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout dialog_barangLayout = new javax.swing.GroupLayout(dialog_barang.getContentPane());
        dialog_barang.getContentPane().setLayout(dialog_barangLayout);
        dialog_barangLayout.setHorizontalGroup(
            dialog_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_barangLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        dialog_barangLayout.setVerticalGroup(
            dialog_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_barangLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1_2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("DATA BARANG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Barang", 0, 0, new java.awt.Font("Berlin Sans FB Demi", 0, 10), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(204, 0, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama Barang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kategori");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Satuan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Qty Min");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Qty Max");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Barcode");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Kode");

        teks_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_namabarangActionPerformed(evt);
            }
        });

        Combo_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_kategoriActionPerformed(evt);
            }
        });

        combo_satuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bungkus", "Dus", "Batang", "Ons", "Grams", "Kilogram" }));

        teks_qtymin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_qtyminActionPerformed(evt);
            }
        });
        teks_qtymin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_qtyminKeyTyped(evt);
            }
        });

        teks_qtymax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_qtymaxKeyTyped(evt);
            }
        });

        teks_kodebarang.setEditable(false);

        label_gambar.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jButton6.setText("Browse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        path_gambar.setText("Path Gambar");

        label_kode_update.setText("jLabel10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(57, 57, 57)
                        .addComponent(teks_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Combo_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teks_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teks_qtymin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teks_qtymax, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(teks_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(label_kode_update)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(path_gambar)
                        .addGap(93, 93, 93))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(teks_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teks_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_kode_update)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(teks_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Combo_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(combo_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teks_qtymin, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(teks_qtymax))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(path_gambar))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Penjualan", 0, 0, new java.awt.Font("Bodoni MT", 0, 10), new java.awt.Color(153, 0, 0))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Harga Jual Sebelum PPN");

        teks_jualppn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_jualppnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_jualppnKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Harga Jual Sesudah PPN");

        teks_jual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_jualKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_jualKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teks_jual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teks_jualppn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(teks_jualppn)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(teks_jual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel12, teks_jual, teks_jualppn});

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Pembelian", 0, 0, null, new java.awt.Color(153, 0, 51)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Harga Beli Sebelum PPN");

        teks_belippn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_belippnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_belippnKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Harga Beli Sesudah PPN");

        teks_beli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_beliKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_beliKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teks_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teks_belippn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, teks_belippn});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(jLabel14)
                .addComponent(teks_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(teks_belippn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, jLabel14, teks_beli, teks_belippn});

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        tombol_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483718_Save.png"))); // NOI18N
        tombol_simpan.setText("SIMPAN");
        tombol_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_simpanActionPerformed(evt);
            }
        });

        tombol_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483766_Delete.png"))); // NOI18N
        tombol_hapus.setText("HAPUS");
        tombol_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_hapusActionPerformed(evt);
            }
        });

        tombol_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483845_Copy.png"))); // NOI18N
        tombol_list.setText("LIST");
        tombol_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_listActionPerformed(evt);
            }
        });

        tombol_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483809_Undo.png"))); // NOI18N
        tombol_batal.setText("BATAL");
        tombol_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_batalActionPerformed(evt);
            }
        });

        tombol_tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442484041_exit.png"))); // NOI18N
        tombol_tutup.setText("TUTUP");
        tombol_tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_tutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tombol_simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombol_hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombol_list, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombol_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombol_tutup)
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tombol_batal, tombol_hapus, tombol_list, tombol_tutup});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(tombol_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_simpan)
                    .addComponent(tombol_tutup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tombol_batal, tombol_hapus, tombol_list, tombol_simpan, tombol_tutup});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    public void tampilisikategori() {
        try {
            List<KategoriBrng> kt = Kontrol_Kategori.getKoneksi().tampilKategori();
            for (int i = 0; i < kt.size(); i++) {
                Combo_kategori.addItem(kt.get(i).getKode() + "  " + kt.get(i).getKategori());
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }


    }
    private void tombol_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_simpanActionPerformed
        // TODO add your handling code here:
        if (teks_namabarang.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "SIlahkan masukkan nama barang");
        } else if (new Integer(teks_qtymax.getText()) < new Integer(teks_qtymin.getText())) {
            JOptionPane.showMessageDialog(null, "QTY MAX tidak boleh lebih kecil dari QTY MIN");
        } else {
            try {
                String kodebrg = teks_kodebarang.getText();
                String barcode = teks_barcode.getText();
                String namabrg = teks_namabarang.getText();
                String satuan = combo_satuan.getSelectedItem().toString();

                String split[] = Combo_kategori.getSelectedItem().toString().split(" ");
                KategoriBrng kat = new KategoriBrng(split[0], " ");
                String kategori = split[0];
                int max = Integer.parseInt(teks_qtymax.getText());
                int min = Integer.parseInt(teks_qtymin.getText());
                FormatRibuan f = new FormatRibuan();
                String beli = f.gabungRibuan(teks_beli.getText());
                String belippn = f.gabungRibuan(teks_belippn.getText());
                String jual = f.gabungRibuan(teks_jual.getText());
                String jualppn = f.gabungRibuan(teks_jualppn.getText());
                double hargajual = Double.parseDouble(teks_jual.getText());
                double hargajualppn = Double.parseDouble(teks_jualppn.getText());
                double hargabeli = Double.parseDouble(teks_beli.getText());
                double hargabelippn = Double.parseDouble(teks_belippn.getText());
                String gambar;
                barang b = new barang();
                if (path_gambar.getText().equals("-")) {
                    gambar = "-";
                    b.setGambar(gambar);
                } else {
                    b.setGambar(kodebrg);
                    gambar = path_gambar.getText();
                    NIOCopier(gambar, gambar(teks_kodebarang.getText()));
                }

                b.setKode(kodebrg);
                b.setBarcode(barcode);
                b.setNamabarang(namabrg);
                b.setKategori(kat);
                b.setSatuan(satuan);
                b.setQtymax(max);
                b.setQtymin(min);
                b.setHargajual(hargajual);
                b.setHargajualppn(hargajualppn);
                b.setHargabeli(hargabeli);
                b.setHargabelippn(hargabelippn);

                Kontrol_barang kb = Kontrol_barang.getKoneksi();
                if (tombol_simpan.getText().equals("SIMPAN")) {
                    kb.tambahBarang(b);
                    JOptionPane.showMessageDialog(null, "Tersimpan");
                    bersittexts();
                } else {
                    kb.updateBarang(b, label_kode_update.getText());
                    JOptionPane.showMessageDialog(null, "Terupdate");
                    bersittexts();
                }
            } catch (IOException ex) {
                Logger.getLogger(GUI_Barang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GUI_Barang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tombol_simpanActionPerformed

    private void tombol_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_hapusActionPerformed
        if (label_kode_update.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Kode barang yang ingin dihapus tidak ada ");
        } else {
            try {
                Kontrol_barang konkat = Kontrol_barang.getKoneksi();
                konkat.hapusBarang(label_kode_update.getText());
                bersittexts();
                JOptionPane.showMessageDialog(null, "Terhapus");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal hapus karena " + ex.getMessage());
            }}
    }//GEN-LAST:event_tombol_hapusActionPerformed

    private void teks_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_namabarangActionPerformed

    private void Combo_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_kategoriActionPerformed
        try {
            // TODO add your handling code here:
            String Combo = Combo_kategori.getSelectedItem().toString();
            String split[] = Combo.split(" ");
            String kodekategori = split[0];
            String bantu;
            int kode = Kontrol_barang.getKoneksi().kodeBarangOtomatis(kodekategori) + 1;
            if (kode == 1) {
                bantu = "001";
                teks_kodebarang.setText(kodekategori + bantu);
            } else if (kode < 10) {
                bantu = "00";
                teks_kodebarang.setText(kodekategori + bantu + kode);
            } else if (10 <= kode && kode < 100) {
                bantu = "0";
                teks_kodebarang.setText(kodekategori + bantu + kode);
            } else {
                teks_kodebarang.setText(kodekategori + kode);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Combo_kategoriActionPerformed

    private void teks_qtyminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_qtyminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_qtyminActionPerformed

    private void teks_qtyminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_qtyminKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_qtyminKeyTyped

    private void teks_qtymaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_qtymaxKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_qtymaxKeyTyped

    private void teks_jualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_jualKeyTyped
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_teks_jualKeyTyped

    private void teks_beliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_beliKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_beliKeyTyped
    public void bersittexts() {
        teks_barcode.setText("");
        teks_namabarang.setText("");
        teks_qtymin.setText("");
        teks_qtymax.setText("");
        teks_beli.setText("");
        teks_belippn.setText("");
        teks_jual.setText("");
        teks_jualppn.setText("");
        Combo_kategori.setSelectedIndex(0);
        combo_satuan.setSelectedIndex(0);
        path_gambar.setText("");
        label_kode_update.setText("");
        tombol_simpan.setText("SIMPAN");
        tombol_hapus.setEnabled(false);
        label_gambar.setIcon(null);

    }
    private void teks_jualppnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_jualppnKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_jualppnKeyTyped

    private void teks_belippnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_belippnKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_belippnKeyTyped

    private void teks_jualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_jualKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() > 1 && !teks_jual.getText().equals("")) {
            FormatRibuan fr = new FormatRibuan();
            teks_jual.setText(fr.gabungRibuan(teks_jual.getText()));
            teks_jual.setText(fr.pisahRibuan(new Integer(teks_jual.getText())));


            int hargajual = new Integer(fr.gabungRibuan(teks_jual.getText())) + new Integer(fr.gabungRibuan(teks_jual.getText())) * 15 / 100;

            teks_jualppn.setText(fr.pisahRibuan((Integer) hargajual));
        }
    }//GEN-LAST:event_teks_jualKeyReleased

    private void teks_jualppnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_jualppnKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() > 1 && !teks_jualppn.getText().equals("")) {
            FormatRibuan fr = new FormatRibuan();
            teks_jualppn.setText(fr.gabungRibuan(teks_jualppn.getText()));
            teks_jualppn.setText(fr.pisahRibuan(new Integer(teks_jualppn.getText())));

            int hargajualppn = new Integer(fr.gabungRibuan(teks_jualppn.getText())) - new Integer(fr.gabungRibuan(teks_jualppn.getText())) * 15 / 100;

            teks_jual.setText(fr.pisahRibuan((Integer) hargajualppn));
        }
    }//GEN-LAST:event_teks_jualppnKeyReleased

    private void teks_beliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_beliKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() > 1 && !teks_beli.getText().equals("")) {
            FormatRibuan fr = new FormatRibuan();
            teks_beli.setText(fr.gabungRibuan(teks_beli.getText()));
            teks_beli.setText(fr.pisahRibuan(new Integer(teks_beli.getText())));

            int hargabeli = new Integer(fr.gabungRibuan(teks_beli.getText())) + new Integer(fr.gabungRibuan(teks_beli.getText())) * 15 / 100;

            teks_belippn.setText(fr.pisahRibuan((Integer) hargabeli));
        }
    }//GEN-LAST:event_teks_beliKeyReleased

    private void teks_belippnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_belippnKeyReleased
        if (evt.getKeyCode() > 1 && !teks_belippn.getText().equals("")) {
            FormatRibuan fr = new FormatRibuan();
            teks_belippn.setText(fr.gabungRibuan(teks_belippn.getText()));
            teks_belippn.setText(fr.pisahRibuan(new Integer(teks_belippn.getText())));

            int hargabelippn = new Integer(fr.gabungRibuan(teks_belippn.getText())) - new Integer(fr.gabungRibuan(teks_belippn.getText())) * 15 / 100;

            teks_beli.setText(fr.pisahRibuan((Integer) hargabelippn));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_teks_belippnKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser jf = new JFileChooser();
        FileFilter jpg, gif, both;
        jpg = new FileNameExtensionFilter("Gambar JPEG", "jpg");
        gif = new FileNameExtensionFilter("Gambar GIF", "gif");
        both = new FileNameExtensionFilter("Gambar JPEG dan GIF", "jpg", "gif");
        jf.setAcceptAllFileFilterUsed(false);
        jf.addChoosableFileFilter(jpg);
        jf.addChoosableFileFilter(gif);
        jf.addChoosableFileFilter(both);
        if (jf.showOpenDialog(this) == jf.APPROVE_OPTION) {
            String f = jf.getSelectedFile().toString();
            path_gambar.setText(f);
            Toolkit tool = Toolkit.getDefaultToolkit();
            Image ig = tool.getImage(f);
            Image im = ig.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
            ImageIcon img = new ImageIcon(im);
            label_gambar.setIcon(img);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tombol_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_listActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        
        tampilBarang();
        dialog_barang.setVisible(true);
    }//GEN-LAST:event_tombol_listActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        try {
            dialog_barang.setVisible(false);

            int row = tabel_barang.getSelectedRow();
            String kode = tabel_barang.getValueAt(row, 1).toString();
            barang brg = Kontrol_barang.getKoneksi().carikodebarang(kode);
            label_kode_update.setText(kode);
            teks_barcode.setText(brg.getBarcode());
            teks_namabarang.setText(brg.getNamabarang());
            teks_qtymin.setText(String.valueOf(brg.getQtymin()));
            teks_qtymax.setText(String.valueOf(brg.getQtymax()));
            teks_beli.setText(String.valueOf(brg.getHargabeli()));
            teks_belippn.setText(String.valueOf(brg.getHargabelippn()));
            teks_jual.setText(String.valueOf(brg.getHargajual()));
            teks_jualppn.setText(String.valueOf(brg.getHargajualppn()));
            Combo_kategori.setSelectedItem(brg.getKategori().getKode() + " " + brg.getKategori());
            combo_satuan.setSelectedItem(brg.getSatuan());
            label_gambar.setIcon(null);
            path_gambar.setText("-");
            // tampil gambar
            if (!brg.getGambar().equals("-")) {
                path_gambar.setText(gambar(kode));
                Toolkit tool = Toolkit.getDefaultToolkit();
                Image ig = tool.getImage(gambar(kode));
                Image im = ig.getScaledInstance(150, 100, Image.SCALE_DEFAULT);
                ImageIcon img = new ImageIcon(im);
                label_gambar.setIcon(img);
            }
            tombol_hapus.setEnabled(true);
            tombol_simpan.setText("UPDATE");
            this.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void tombol_tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_tutupActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_tombol_tutupActionPerformed

    private void tombol_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_batalActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_tombol_batalActionPerformed

    private String gambar(String id) {
        return folder + File.separator + (id.trim() + ".jpg");
    }

    private void cetak(String str) {
        System.out.println(str);
    }

    public static void NIOCopier(String asal, String tujuan) throws IOException {
        FileInputStream inFile = new FileInputStream(asal);
        FileOutputStream outFile = new FileOutputStream(tujuan);
        FileChannel inChannel = inFile.getChannel();
        FileChannel outChannel = outFile.getChannel();
        for (ByteBuffer buffer = ByteBuffer.allocate(1024 * 1024);
                inChannel.read(buffer) != -1;
                buffer.clear()) {
            buffer.flip();
            while (buffer.hasRemaining()) {
                outChannel.write(buffer);
            }
        }
        inChannel.close();
        outChannel.close();
    }

    public void tampilBarang() {
        try {
            List<barang> kat = Kontrol_barang.getKoneksi().tampilBarang();
            TabelModel_Barang model = new TabelModel_Barang(kat);
            tabel_barang.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GUI_Barang dialog = new GUI_Barang(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_kategori;
    private javax.swing.JComboBox combo_satuan;
    private javax.swing.JDialog dialog_barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_gambar;
    private javax.swing.JLabel label_kode_update;
    private javax.swing.JLabel path_gambar;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTextField teks_barcode;
    private javax.swing.JTextField teks_beli;
    private javax.swing.JTextField teks_belippn;
    private javax.swing.JTextField teks_jual;
    private javax.swing.JTextField teks_jualppn;
    private javax.swing.JTextField teks_kodebarang;
    private javax.swing.JTextField teks_namabarang;
    private javax.swing.JTextField teks_qtymax;
    private javax.swing.JTextField teks_qtymin;
    private javax.swing.JButton tombol_batal;
    private javax.swing.JButton tombol_hapus;
    private javax.swing.JButton tombol_list;
    private javax.swing.JButton tombol_simpan;
    private javax.swing.JButton tombol_tutup;
    // End of variables declaration//GEN-END:variables

    public class FormatRibuan {

        public FormatRibuan() {
        }

        public String pisahRibuan(int key) {
            DecimalFormat df = new DecimalFormat("###,###.##");
            String bantu = df.format(key);
            return bantu;
        }

        public String gabungRibuan(String key) {
            String ribuan[] = key.split("\\.");
            String bantu = "";
            for (int i = 0; i < ribuan.length; i++) {
                bantu = bantu + ribuan[i];
            }
            return bantu;
        }
    }
}
