/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Kategori;

import java.awt.JobAttributes;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author basisb21la
 */
public class GUI_Kategori extends java.awt.Dialog {

    /**
     * Creates new form GUI_Kategori
     */
    public GUI_Kategori(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        tampilKategori();
        label_kode.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TEKS_KODE = new javax.swing.JTextField();
        TEKS_NAMAKATEGORI = new javax.swing.JTextField();
        TOMBOLSIMPAN = new javax.swing.JButton();
        TOMBOLHAPUS = new javax.swing.JButton();
        TOMBOLBATAL = new javax.swing.JButton();
        TOMBOLTUTUP = new javax.swing.JButton();
        label_kode = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABEL_LISTKATEGORI = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mobil.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mobil.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("KATEGORI BARANG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addGap(84, 84, 84)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel4.setText("Kode Kategori");

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel5.setText("Nama Kategori");

        TOMBOLSIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483718_Save.png"))); // NOI18N
        TOMBOLSIMPAN.setText("Simpan");
        TOMBOLSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOMBOLSIMPANActionPerformed(evt);
            }
        });

        TOMBOLHAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483766_Delete.png"))); // NOI18N
        TOMBOLHAPUS.setText("Hapus");
        TOMBOLHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOMBOLHAPUSActionPerformed(evt);
            }
        });

        TOMBOLBATAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483809_Undo.png"))); // NOI18N
        TOMBOLBATAL.setText("Batal");
        TOMBOLBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOMBOLBATALActionPerformed(evt);
            }
        });

        TOMBOLTUTUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442484041_exit.png"))); // NOI18N
        TOMBOLTUTUP.setText("Tutup");
        TOMBOLTUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOMBOLTUTUPActionPerformed(evt);
            }
        });

        label_kode.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TOMBOLSIMPAN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TOMBOLHAPUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TOMBOLBATAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TOMBOLTUTUP))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TEKS_KODE, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TEKS_NAMAKATEGORI))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TEKS_KODE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TEKS_NAMAKATEGORI))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOMBOLSIMPAN)
                    .addComponent(TOMBOLHAPUS)
                    .addComponent(TOMBOLBATAL)
                    .addComponent(TOMBOLTUTUP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LIST DATA KATEGORI BARANG", 0, 0, new java.awt.Font("Goudy Old Style", 1, 18))); // NOI18N

        TABEL_LISTKATEGORI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode", "Kategori"
            }
        ));
        TABEL_LISTKATEGORI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABEL_LISTKATEGORIMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABEL_LISTKATEGORI);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TOMBOLBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOMBOLBATALActionPerformed
bersihTeks();        // TODO add your handling code here:
    }//GEN-LAST:event_TOMBOLBATALActionPerformed

    private void TOMBOLSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOMBOLSIMPANActionPerformed
        // TODO add your handling code here:
        if (TEKS_KODE.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Silahkan isi Kode Kategori");}
        else if (TEKS_NAMAKATEGORI.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Silahkan isi Nama Kategori");    
        }
        else {
            try {
                String kode=TEKS_KODE.getText();
                String kategori = TEKS_NAMAKATEGORI.getText();
                KategoriBrng kat=new KategoriBrng();
                kat.setKode(kode);
                kat.setKategori(kategori);
                KategoriBrng kk=Kontrol_Kategori.getKoneksi().carikodeKategori(kode);
                
                if (kode.equals(kk.getKode())&&! TOMBOLSIMPAN.getText().equals("UPDATE")){
                    JOptionPane.showMessageDialog(null,"Maaf kode "+kode+" sudah digunakan ");
                } else {
                    Kontrol_Kategori konkat=Kontrol_Kategori.getKoneksi();
                if (TOMBOLSIMPAN.getText().equals("UPDATE")) {
                    konkat.updateKategori(kat,label_kode.getText());
                    bersihTeks();
                JOptionPane.showMessageDialog(null,"Terupdate");
                }else {
                konkat.tambahKategori(kat);
                bersihTeks();
                JOptionPane.showMessageDialog(null,"Tersimpan");
                }
                }
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Gagal menyimpan karena "+ex.getMessage());
            }
    }//GEN-LAST:event_TOMBOLSIMPANActionPerformed
    }
        private void TABEL_LISTKATEGORIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABEL_LISTKATEGORIMouseClicked
        int row=TABEL_LISTKATEGORI.getSelectedRow();
        String kode=TABEL_LISTKATEGORI.getValueAt(row, 1).toString();
        String kategori=TABEL_LISTKATEGORI.getValueAt(row, 2).toString();
        label_kode.setText(kode);
        TEKS_KODE.setText(kode);
        TEKS_NAMAKATEGORI.setText(kategori);
        TOMBOLSIMPAN.setText("UPDATE");
        //to string berguna untuk tipe data apapun akan di String kan
    }//GEN-LAST:event_TABEL_LISTKATEGORIMouseClicked

    private void TOMBOLHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOMBOLHAPUSActionPerformed
        if (TEKS_KODE.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Maaf, Kode barang yang ingin dihapus tidak ada ");
        }
        else    {
       try{
           Kontrol_Kategori konkat=Kontrol_Kategori.getKoneksi();
           konkat.hapusKategori(TEKS_KODE.getText());
           bersihTeks();
           JOptionPane.showMessageDialog(null,"Terhapus");
       } catch (SQLException ex){
           JOptionPane.showMessageDialog(null,"Gagal hapus karena "+ex.getMessage());
       }
    }//GEN-LAST:event_TOMBOLHAPUSActionPerformed
    }
        private void TOMBOLTUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOMBOLTUTUPActionPerformed
       this.dispose(); //atau this.Visible(false) . jangan pakai system exit(o) karena program akan tertutup semua
    }//GEN-LAST:event_TOMBOLTUTUPActionPerformed
    
    public void bersihTeks(){
        label_kode.setText("");
        TEKS_KODE.setText("");
        TEKS_NAMAKATEGORI.setText("");
        tampilKategori();
        TOMBOLSIMPAN.setText("SIMPAN");
        
    }
    public void tampilKategori(){
        try {
            List<KategoriBrng> kat=Kontrol_Kategori.getKoneksi().tampilKategori();
            TabelModel_Kategori model=new TabelModel_Kategori(kat);
            TABEL_LISTKATEGORI.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Kategori.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GUI_Kategori dialog = new GUI_Kategori(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABEL_LISTKATEGORI;
    private javax.swing.JTextField TEKS_KODE;
    private javax.swing.JTextField TEKS_NAMAKATEGORI;
    private javax.swing.JButton TOMBOLBATAL;
    private javax.swing.JButton TOMBOLHAPUS;
    private javax.swing.JButton TOMBOLSIMPAN;
    private javax.swing.JButton TOMBOLTUTUP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_kode;
    // End of variables declaration//GEN-END:variables
}
